version: "3.8"
services:
  app:
    build: .
    container_name: news-next
    working_dir: /app
    user: "1000:1000"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "pnpm install && pnpm run dev"
    networks:
      - news-network

networks:
  news-network:
    driver: bridge
